stages:
  - build

build-code-test:
  stage: build
  only:
    - testing
  tags:
    - testing
  script:
    - echo "Start"
    - cd /var/www/acreditacion-rrii-backend
    - sudo git checkout testing
    - sudo git pull https://$GLAB_USER:$GLAB_PASS@gitlab.com/4rian903/acreditacion-rrii-backend.git
    - sudo composer install
    - sudo php artisan migrate
    - echo "End"

