stages:
  - test
  - production

build-test:
  stage: test
  only:
    - testing
  tags:
    - testing-backend
  script:
    - echo "Start build test"
    - cd /var/www/acreditacion-rrii-backend
    - sudo git checkout testing
    - sudo git pull
    - sudo php artisan migrate
    - echo "End build test"

build-production:
  stage: build
  only:
    - main
  tags:
    - production-backend
  script:
    - echo "Start build production"
    - cd /var/www/acreditacion-rrii-backend
    - sudo git checkout main
    - sudo git pull
    - sudo php artisan migrate
    - echo "End build production"
