stages:
  - build

build-code-test:
  stage: build
  only:
    - testing
  tags:
    - testing
  script:
    - echo "Start build test"
    - cd /var/www/acreditacion-rrii-backend
    - sudo git checkout testing
    - sudo git pull
    - sudo php artisan migrate
    - echo "End build test"

