version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: rr-ii-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/backend
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - rr-ii
  app:
    build:
      #args:
        #user: prod
        #uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: rrii-backend-app
    restart: unless-stopped
    working_dir: /var/www/backend
    volumes:
      - ./:/var/www/backend
    networks:
      - rr-ii

networks:
  rr-ii:
    driver: bridge
